// Code generated by tools/normgen. DO NOT EDIT.

package participant

import (
	"strings"
)

func normalizeJoinBase(message Join) Join {
	message.Name = strings.TrimSpace(message.Name)
	return message
}

func normalizeUpdate(message Update) Update {
	message.Name = strings.TrimSpace(message.Name)
	return message
}

func normalizeBind(message Bind) Bind {
	return message
}

func normalizeUnbind(message Unbind) Unbind {
	return message
}

func normalizeLeave(message Leave) Leave {
	message.Reason = strings.TrimSpace(message.Reason)
	return message
}

func normalizeJoined(message Joined) Joined {
	message.Name = strings.TrimSpace(message.Name)
	return message
}

func normalizeUpdated(message Updated) Updated {
	message.Name = strings.TrimSpace(message.Name)
	return message
}

func normalizeBound(message Bound) Bound {
	return message
}

func normalizeUnbound(message Unbound) Unbound {
	return message
}

func normalizeLeft(message Left) Left {
	return message
}
