// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package db

import (
	"context"
)

const getArtifact = `-- name: GetArtifact :one
SELECT content, updated_at_ns
FROM campaign_artifacts
WHERE campaign_id = ? AND path = ?
`

type GetArtifactParams struct {
	CampaignID string
	Path       string
}

type GetArtifactRow struct {
	Content     string
	UpdatedAtNs int64
}

func (q *Queries) GetArtifact(ctx context.Context, arg GetArtifactParams) (GetArtifactRow, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, arg.CampaignID, arg.Path)
	var i GetArtifactRow
	err := row.Scan(&i.Content, &i.UpdatedAtNs)
	return i, err
}

const listArtifactsByCampaign = `-- name: ListArtifactsByCampaign :many
SELECT path, content, updated_at_ns
FROM campaign_artifacts
WHERE campaign_id = ?
ORDER BY path
`

type ListArtifactsByCampaignRow struct {
	Path        string
	Content     string
	UpdatedAtNs int64
}

func (q *Queries) ListArtifactsByCampaign(ctx context.Context, campaignID string) ([]ListArtifactsByCampaignRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtifactsByCampaign, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArtifactsByCampaignRow{}
	for rows.Next() {
		var i ListArtifactsByCampaignRow
		if err := rows.Scan(&i.Path, &i.Content, &i.UpdatedAtNs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putArtifact = `-- name: PutArtifact :exec
INSERT INTO campaign_artifacts (campaign_id, path, content, updated_at_ns)
VALUES (?, ?, ?, ?)
ON CONFLICT(campaign_id, path) DO UPDATE SET
	content = excluded.content,
	updated_at_ns = excluded.updated_at_ns
`

type PutArtifactParams struct {
	CampaignID  string
	Path        string
	Content     string
	UpdatedAtNs int64
}

func (q *Queries) PutArtifact(ctx context.Context, arg PutArtifactParams) error {
	_, err := q.db.ExecContext(ctx, putArtifact,
		arg.CampaignID,
		arg.Path,
		arg.Content,
		arg.UpdatedAtNs,
	)
	return err
}
