// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
)

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO campaign_events (
	campaign_id, seq, commit_seq, recorded_at_ns, event_type, payload_blob
) VALUES (?, ?, ?, ?, ?, ?)
`

type AppendEventParams struct {
	CampaignID   string
	Seq          int64
	CommitSeq    int64
	RecordedAtNs int64
	EventType    string
	PayloadBlob  []byte
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.ExecContext(ctx, appendEvent,
		arg.CampaignID,
		arg.Seq,
		arg.CommitSeq,
		arg.RecordedAtNs,
		arg.EventType,
		arg.PayloadBlob,
	)
	return err
}

const getEventHead = `-- name: GetEventHead :one
SELECT
	CAST(COUNT(*) AS INTEGER) AS event_count,
	CAST(COALESCE(MAX(seq), 0) AS INTEGER) AS head_seq,
	CAST(COALESCE(MAX(commit_seq), 0) AS INTEGER) AS head_commit_seq
FROM campaign_events
WHERE campaign_id = ?
`

type GetEventHeadRow struct {
	EventCount    int64
	HeadSeq       int64
	HeadCommitSeq int64
}

func (q *Queries) GetEventHead(ctx context.Context, campaignID string) (GetEventHeadRow, error) {
	row := q.db.QueryRowContext(ctx, getEventHead, campaignID)
	var i GetEventHeadRow
	err := row.Scan(&i.EventCount, &i.HeadSeq, &i.HeadCommitSeq)
	return i, err
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT seq, commit_seq, recorded_at_ns, event_type, payload_blob
FROM campaign_events
WHERE campaign_id = ? AND seq > ?
ORDER BY seq
`

type ListEventsAfterParams struct {
	CampaignID string
	Seq        int64
}

type ListEventsAfterRow struct {
	Seq          int64
	CommitSeq    int64
	RecordedAtNs int64
	EventType    string
	PayloadBlob  []byte
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]ListEventsAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsAfter, arg.CampaignID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsAfterRow{}
	for rows.Next() {
		var i ListEventsAfterRow
		if err := rows.Scan(
			&i.Seq,
			&i.CommitSeq,
			&i.RecordedAtNs,
			&i.EventType,
			&i.PayloadBlob,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
