// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type CampaignArtifact struct {
	CampaignID  string
	Path        string
	Content     string
	UpdatedAtNs int64
}

type CampaignEvent struct {
	CampaignID   string
	Seq          int64
	CommitSeq    int64
	RecordedAtNs int64
	EventType    string
	PayloadBlob  []byte
}

type ProjectionCampaignSubject struct {
	SubjectID  string
	CampaignID string
}

type ProjectionCampaignSummary struct {
	CampaignID       string
	Name             string
	ReadyToPlay      int64
	HasAiBinding     int64
	HasActiveSession int64
	LastActivityAtNs int64
	UpdatedAtNs      int64
}

type ProjectionSnapshot struct {
	CampaignID       string
	HeadSeq          int64
	StateBlob        []byte
	UpdatedAtNs      int64
	LastActivityAtNs int64
}

type ProjectionWatermark struct {
	CampaignID      string
	AppliedSeq      int64
	ExpectedNextSeq int64
	UpdatedAtNs     int64
}
