// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projections.sql

package db

import (
	"context"
)

const deleteCampaignSubjects = `-- name: DeleteCampaignSubjects :exec
DELETE FROM projection_campaign_subjects
WHERE campaign_id = ?
`

func (q *Queries) DeleteCampaignSubjects(ctx context.Context, campaignID string) error {
	_, err := q.db.ExecContext(ctx, deleteCampaignSubjects, campaignID)
	return err
}

const getProjection = `-- name: GetProjection :one
SELECT head_seq, state_blob, updated_at_ns, last_activity_at_ns
FROM projection_snapshots
WHERE campaign_id = ?
`

type GetProjectionRow struct {
	HeadSeq          int64
	StateBlob        []byte
	UpdatedAtNs      int64
	LastActivityAtNs int64
}

func (q *Queries) GetProjection(ctx context.Context, campaignID string) (GetProjectionRow, error) {
	row := q.db.QueryRowContext(ctx, getProjection, campaignID)
	var i GetProjectionRow
	err := row.Scan(
		&i.HeadSeq,
		&i.StateBlob,
		&i.UpdatedAtNs,
		&i.LastActivityAtNs,
	)
	return i, err
}

const getWatermark = `-- name: GetWatermark :one
SELECT applied_seq, expected_next_seq, updated_at_ns
FROM projection_watermarks
WHERE campaign_id = ?
`

type GetWatermarkRow struct {
	AppliedSeq      int64
	ExpectedNextSeq int64
	UpdatedAtNs     int64
}

func (q *Queries) GetWatermark(ctx context.Context, campaignID string) (GetWatermarkRow, error) {
	row := q.db.QueryRowContext(ctx, getWatermark, campaignID)
	var i GetWatermarkRow
	err := row.Scan(&i.AppliedSeq, &i.ExpectedNextSeq, &i.UpdatedAtNs)
	return i, err
}

const listCampaignsBySubject = `-- name: ListCampaignsBySubject :many
SELECT
	s.campaign_id,
	s.name,
	s.ready_to_play,
	s.has_ai_binding,
	s.has_active_session,
	s.last_activity_at_ns
FROM projection_campaign_subjects AS idx
JOIN projection_campaign_summaries AS s ON s.campaign_id = idx.campaign_id
WHERE idx.subject_id = ?
ORDER BY s.last_activity_at_ns DESC, s.campaign_id ASC
LIMIT ?
`

type ListCampaignsBySubjectParams struct {
	SubjectID string
	Limit     int64
}

type ListCampaignsBySubjectRow struct {
	CampaignID       string
	Name             string
	ReadyToPlay      int64
	HasAiBinding     int64
	HasActiveSession int64
	LastActivityAtNs int64
}

func (q *Queries) ListCampaignsBySubject(ctx context.Context, arg ListCampaignsBySubjectParams) ([]ListCampaignsBySubjectRow, error) {
	rows, err := q.db.QueryContext(ctx, listCampaignsBySubject, arg.SubjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCampaignsBySubjectRow{}
	for rows.Next() {
		var i ListCampaignsBySubjectRow
		if err := rows.Scan(
			&i.CampaignID,
			&i.Name,
			&i.ReadyToPlay,
			&i.HasAiBinding,
			&i.HasActiveSession,
			&i.LastActivityAtNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectionSnapshotsForBackfill = `-- name: ListProjectionSnapshotsForBackfill :many
SELECT p.campaign_id, p.head_seq, p.state_blob, p.updated_at_ns, p.last_activity_at_ns
FROM projection_snapshots AS p
LEFT JOIN projection_campaign_summaries AS s ON s.campaign_id = p.campaign_id
WHERE s.campaign_id IS NULL
ORDER BY p.campaign_id ASC
`

func (q *Queries) ListProjectionSnapshotsForBackfill(ctx context.Context) ([]ProjectionSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listProjectionSnapshotsForBackfill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectionSnapshot{}
	for rows.Next() {
		var i ProjectionSnapshot
		if err := rows.Scan(
			&i.CampaignID,
			&i.HeadSeq,
			&i.StateBlob,
			&i.UpdatedAtNs,
			&i.LastActivityAtNs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putCampaignSubject = `-- name: PutCampaignSubject :exec
INSERT INTO projection_campaign_subjects (subject_id, campaign_id)
VALUES (?, ?)
ON CONFLICT(subject_id, campaign_id) DO NOTHING
`

type PutCampaignSubjectParams struct {
	SubjectID  string
	CampaignID string
}

func (q *Queries) PutCampaignSubject(ctx context.Context, arg PutCampaignSubjectParams) error {
	_, err := q.db.ExecContext(ctx, putCampaignSubject, arg.SubjectID, arg.CampaignID)
	return err
}

const putCampaignSummary = `-- name: PutCampaignSummary :exec
INSERT INTO projection_campaign_summaries (
	campaign_id, name, ready_to_play, has_ai_binding, has_active_session, last_activity_at_ns, updated_at_ns
)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(campaign_id) DO UPDATE SET
	name = excluded.name,
	ready_to_play = excluded.ready_to_play,
	has_ai_binding = excluded.has_ai_binding,
	has_active_session = excluded.has_active_session,
	last_activity_at_ns = excluded.last_activity_at_ns,
	updated_at_ns = excluded.updated_at_ns
`

type PutCampaignSummaryParams struct {
	CampaignID       string
	Name             string
	ReadyToPlay      int64
	HasAiBinding     int64
	HasActiveSession int64
	LastActivityAtNs int64
	UpdatedAtNs      int64
}

func (q *Queries) PutCampaignSummary(ctx context.Context, arg PutCampaignSummaryParams) error {
	_, err := q.db.ExecContext(ctx, putCampaignSummary,
		arg.CampaignID,
		arg.Name,
		arg.ReadyToPlay,
		arg.HasAiBinding,
		arg.HasActiveSession,
		arg.LastActivityAtNs,
		arg.UpdatedAtNs,
	)
	return err
}

const putProjection = `-- name: PutProjection :exec
INSERT INTO projection_snapshots (campaign_id, head_seq, state_blob, updated_at_ns, last_activity_at_ns)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(campaign_id) DO UPDATE SET
	head_seq = excluded.head_seq,
	state_blob = excluded.state_blob,
	updated_at_ns = excluded.updated_at_ns,
	last_activity_at_ns = excluded.last_activity_at_ns
`

type PutProjectionParams struct {
	CampaignID       string
	HeadSeq          int64
	StateBlob        []byte
	UpdatedAtNs      int64
	LastActivityAtNs int64
}

func (q *Queries) PutProjection(ctx context.Context, arg PutProjectionParams) error {
	_, err := q.db.ExecContext(ctx, putProjection,
		arg.CampaignID,
		arg.HeadSeq,
		arg.StateBlob,
		arg.UpdatedAtNs,
		arg.LastActivityAtNs,
	)
	return err
}

const putWatermark = `-- name: PutWatermark :exec
INSERT INTO projection_watermarks (campaign_id, applied_seq, expected_next_seq, updated_at_ns)
VALUES (?, ?, ?, ?)
ON CONFLICT(campaign_id) DO UPDATE SET
	applied_seq = excluded.applied_seq,
	expected_next_seq = excluded.expected_next_seq,
	updated_at_ns = excluded.updated_at_ns
`

type PutWatermarkParams struct {
	CampaignID      string
	AppliedSeq      int64
	ExpectedNextSeq int64
	UpdatedAtNs     int64
}

func (q *Queries) PutWatermark(ctx context.Context, arg PutWatermarkParams) error {
	_, err := q.db.ExecContext(ctx, putWatermark,
		arg.CampaignID,
		arg.AppliedSeq,
		arg.ExpectedNextSeq,
		arg.UpdatedAtNs,
	)
	return err
}
