// Code generated by tools/normgen. DO NOT EDIT.

package character

import (
	"strings"
)

func normalizeCreateBase(message Create) Create {
	message.Name = strings.TrimSpace(message.Name)
	return message
}

func normalizeUpdateBase(message Update) Update {
	message.Name = strings.TrimSpace(message.Name)
	return message
}

func normalizeDelete(message Delete) Delete {
	message.Reason = strings.TrimSpace(message.Reason)
	return message
}

func normalizeCreatedBase(message Created) Created {
	message.Name = strings.TrimSpace(message.Name)
	return message
}

func normalizeUpdatedBase(message Updated) Updated {
	message.Name = strings.TrimSpace(message.Name)
	return message
}

func normalizeDeleted(message Deleted) Deleted {
	return message
}
