// Code generated by tools/normgen. DO NOT EDIT.

package session

import (
	"strings"
)

func normalizeStart(message Start) Start {
	message.Name = strings.TrimSpace(message.Name)
	message.CharacterControllers = CloneAssignments(message.CharacterControllers)
	return message
}

func normalizeStarted(message Started) Started {
	message.Name = strings.TrimSpace(message.Name)
	message.CharacterControllers = CloneAssignments(message.CharacterControllers)
	return message
}

func normalizeEnded(message Ended) Ended {
	message.Name = strings.TrimSpace(message.Name)
	message.CharacterControllers = CloneAssignments(message.CharacterControllers)
	return message
}
