// Code generated by tools/normgen. DO NOT EDIT.

package scene

import (
	"strings"
)

func normalizeCreate(message Create) Create {
	message.Name = strings.TrimSpace(message.Name)
	message.CharacterIDs = CloneCharacterIDs(message.CharacterIDs)
	return message
}

func normalizeActivate(message Activate) Activate {
	return message
}

func normalizeEnd(message End) End {
	return message
}

func normalizeReplaceCast(message ReplaceCast) ReplaceCast {
	message.CharacterIDs = CloneCharacterIDs(message.CharacterIDs)
	return message
}

func normalizeCreated(message Created) Created {
	message.Name = strings.TrimSpace(message.Name)
	message.CharacterIDs = CloneCharacterIDs(message.CharacterIDs)
	return message
}

func normalizeActivated(message Activated) Activated {
	return message
}

func normalizeEnded(message Ended) Ended {
	return message
}

func normalizeCastReplacedEvent(message CastReplaced) CastReplaced {
	message.CharacterIDs = CloneCharacterIDs(message.CharacterIDs)
	return message
}
