package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateAndCheckPackage(t *testing.T) {
	root := t.TempDir()
	mustWriteFile(t, filepath.Join(root, "internal", "sample", "sample.go"), `package sample

type Mode string

type Example struct {
	Name string
	Mode Mode
	IDs  []string
}

func cloneIDs(input []string) []string { return input }
`)

	spec := packageSpec{
		Dir:    "internal/sample",
		Output: "internal/sample/zz_normalize.go",
		Functions: []functionSpec{
			{
				Name:     "normalizeExample",
				TypeName: "Example",
				Mode:     functionModeFinal,
				Ops: []fieldOp{
					{Kind: fieldOpTrimString, FieldName: "Name"},
					{Kind: fieldOpTrimStringCast, FieldName: "Mode"},
					{Kind: fieldOpNormalizeStringList, FieldName: "IDs", Trim: true, DropEmpty: true, Unique: true, Sort: true},
				},
			},
		},
	}

	g := newGenerator(root)
	if err := g.generateAll([]packageSpec{spec}); err != nil {
		t.Fatalf("generateAll() error = %v", err)
	}

	outputPath := filepath.Join(root, "internal", "sample", "zz_normalize.go")
	generated, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("ReadFile(%s) error = %v", outputPath, err)
	}
	text := string(generated)
	for _, want := range []string{
		"Code generated by tools/normgen. DO NOT EDIT.",
		"func normalizeExample(message Example) Example",
		`message.Name = strings.TrimSpace(message.Name)`,
		`message.Mode = Mode(strings.TrimSpace(string(message.Mode)))`,
		`message.IDs = zzNormalizeStringSlice(message.IDs, true, true, true, true)`,
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("generated file missing %q\n%s", want, text)
		}
	}

	if err := g.checkAll([]packageSpec{spec}); err != nil {
		t.Fatalf("checkAll() error = %v", err)
	}
}

func TestCheckFailsOnStaleGeneratedFile(t *testing.T) {
	root := t.TempDir()
	mustWriteFile(t, filepath.Join(root, "internal", "sample", "sample.go"), `package sample

type Example struct {
	Name string
}
`)
	mustWriteFile(t, filepath.Join(root, "internal", "sample", "zz_normalize.go"), "package sample\n")

	g := newGenerator(root)
	err := g.checkAll([]packageSpec{{
		Dir:    "internal/sample",
		Output: "internal/sample/zz_normalize.go",
		Functions: []functionSpec{{
			Name:     "normalizeExample",
			TypeName: "Example",
			Mode:     functionModeFinal,
			Ops:      []fieldOp{{Kind: fieldOpTrimString, FieldName: "Name"}},
		}},
	}})
	if err == nil || !strings.Contains(err.Error(), "stale") {
		t.Fatalf("checkAll() error = %v, want stale error", err)
	}
}

func TestValidatePackageSpecErrors(t *testing.T) {
	root := t.TempDir()
	mustWriteFile(t, filepath.Join(root, "internal", "sample", "sample.go"), `package sample

type Mode string

type Example struct {
	Name string
	Mode Mode
	IDs  []string
}
`)

	g := newGenerator(root)
	meta, err := g.loadPackageMeta("internal/sample")
	if err != nil {
		t.Fatalf("loadPackageMeta() error = %v", err)
	}

	cases := []struct {
		name string
		spec packageSpec
		want string
	}{
		{
			name: "missing type",
			spec: packageSpec{
				Dir:    "internal/sample",
				Output: "internal/sample/zz_normalize.go",
				Functions: []functionSpec{{
					Name:     "normalizeMissing",
					TypeName: "Missing",
					Mode:     functionModeFinal,
				}},
			},
			want: "type Missing not found",
		},
		{
			name: "missing field",
			spec: packageSpec{
				Dir:    "internal/sample",
				Output: "internal/sample/zz_normalize.go",
				Functions: []functionSpec{{
					Name:     "normalizeExample",
					TypeName: "Example",
					Mode:     functionModeFinal,
					Ops:      []fieldOp{{Kind: fieldOpTrimString, FieldName: "Missing"}},
				}},
			},
			want: "field Missing not found",
		},
		{
			name: "wrong trim cast type",
			spec: packageSpec{
				Dir:    "internal/sample",
				Output: "internal/sample/zz_normalize.go",
				Functions: []functionSpec{{
					Name:     "normalizeExample",
					TypeName: "Example",
					Mode:     functionModeFinal,
					Ops:      []fieldOp{{Kind: fieldOpTrimStringCast, FieldName: "Name"}},
				}},
			},
			want: "must be named string",
		},
		{
			name: "missing helper",
			spec: packageSpec{
				Dir:    "internal/sample",
				Output: "internal/sample/zz_normalize.go",
				Functions: []functionSpec{{
					Name:     "normalizeExample",
					TypeName: "Example",
					Mode:     functionModeFinal,
					Ops:      []fieldOp{{Kind: fieldOpCall, FieldName: "IDs", Helper: "missingHelper"}},
				}},
			},
			want: "helper missingHelper not found",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			err := validatePackageSpec(tc.spec, meta)
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Fatalf("validatePackageSpec() error = %v, want substring %q", err, tc.want)
			}
		})
	}
}

func mustWriteFile(t *testing.T, path string, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("MkdirAll(%s) error = %v", path, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("WriteFile(%s) error = %v", path, err)
	}
}
