// Code generated by tools/normgen. DO NOT EDIT.

package campaign

import (
	"strings"
)

func normalizeCreate(message Create) Create {
	message.Name = strings.TrimSpace(message.Name)
	message.OwnerName = strings.TrimSpace(message.OwnerName)
	return message
}

func normalizeUpdate(message Update) Update {
	message.Name = strings.TrimSpace(message.Name)
	return message
}

func normalizeAIBind(message AIBind) AIBind {
	return message
}

func normalizePlayPause(message PlayPause) PlayPause {
	message.Reason = strings.TrimSpace(message.Reason)
	return message
}

func normalizePlayResume(message PlayResume) PlayResume {
	message.Reason = strings.TrimSpace(message.Reason)
	return message
}

func normalizeCreated(message Created) Created {
	message.Name = strings.TrimSpace(message.Name)
	return message
}

func normalizeUpdated(message Updated) Updated {
	message.Name = strings.TrimSpace(message.Name)
	return message
}

func normalizeAIBound(message AIBound) AIBound {
	return message
}

func normalizePlayBegan(message PlayBegan) PlayBegan {
	return message
}

func normalizePlayPaused(message PlayPaused) PlayPaused {
	message.Reason = strings.TrimSpace(message.Reason)
	return message
}

func normalizePlayResumed(message PlayResumed) PlayResumed {
	message.Reason = strings.TrimSpace(message.Reason)
	return message
}

func normalizePlayEnded(message PlayEnded) PlayEnded {
	return message
}
